# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Scala CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: write # this permission is needed to submit the dependency graph

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v4

    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: 'sbt'

    - name: Create project secret files
      env:
        dev_secrets: ${{ secrets.DEV }}
        prod_secrets: ${{ secrets.PROD }}
      run: |
        echo "$dev_secrets" > .secrets-dev
        echo "$prod_secrets" > .secrets-prod

    - name: Run tests
      run: |
        sbt -J-Xmx3G test

    # Optional: This step uploads information to the GitHub dependency graph, unblocking Dependabot alerts for the
    # repository
    - name: Upload dependency graph
      uses: scalacenter/sbt-dependency-submission@v2
